services:
  - type: worker
    name: wos-discord-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python "PROJECT_MIGRATION/app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
